name: 'Set up hctl platform-orchestrator CLI'
author: humanitec
description: |-
  Downloads, installs, and configures the hctl CLI.
  Adds the `hctl` CLI command to the $PATH.
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  version:
    required: false
    default: '1'
  token:
    description: 'GitHub token (required if a version range is specified)'
    required: false
outputs: {}
runs:
  using: node20
  main: dist/index.js
